# UdonTur's Hyprland Configuration
# Web: https://hadrianlau.com
# GitHub: @udontur

source = ~/.config/hypr/hypr/system.conf
source = ~/.config/hypr/hypr/style.conf
source = ~/.config/hypr/hypr/bind.conf
