# Launch on start programs
exec-once = hyprpaper
exec-once = waybar
exec-once = firefox
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Environment Variables
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = HYPRCURSOR_THEME, Bibata-Modern-Ice
env = HYPRCURSOR_SIZE, 25
env = XCURSOR_THEME, Bibata-Modern-Ice
env = XCURSOR_SIZE, 25
env = GTK_THEME, Adwaita-dark

# Monitors
monitor=eDP-1, 1920x1200@60, 0x0, 1.333333
